// <auto-generated />
using CsvImporter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CsvImporter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210512004516_TableStockAddCompositeKeyNew")]
    partial class TableStockAddCompositeKeyNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CsvImporter.Models.StockModel", b =>
                {
                    b.Property<string>("PointOfSale")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Stock")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PointOfSale", "Product", "Date", "Stock");

                    b.ToTable("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
