name: .NET Core Build with Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    # use ubuntu for more build minutes
    runs-on: ubuntu-latest
    # use release mode for all steps
 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x    

      # restore dependencies  
    - name: Install dependencies
      run: dotnet restore ./CsvImporter/CsvImporter.sln

      # build project
    - name: Build
      run: dotnet build ./CsvImporter/CsvImporter.sln --configuration $config --no-restore
      
      # run tests project
    - name: Tests      
      run: dotnet test   --configuration 
